# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a60f98f688c8c54280c0ffd481b635dea6c9d4721f9c1214eafa037226695a555ec095d07ab8af1242dd1a53f75c537d11b62e809f00abf2c1aebe8afd55fa5

test:
  secret_key_base: 6d03aac76670e9ea580c1eff173833333bce244563c69c4f02f5f169bf77c23d00c6cb58505a5d3c6e5bf691772272d17d163b49e5e6a264e249835db8f00ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
